name: "Azure Blob Storage Download"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      target_folder:
        required: true
        type: string
      export_file_name:
        required: true
        type: string
      tf_backend_storage_account:
        required: true
        type: string
      tf_backend_container:
        required: true
        type: string
      dir_artifact_name:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Create working directories'
        run: |
          mkdir -p "$RUNNER_TEMP/${{ inputs.target_folder }}"
          mkdir -p "${{ inputs.target_folder }}"

      - name: 'Issue with Github Action Repository'
        run: |
          curl --location -s https://mcr.microsoft.com/v2/azure-cli/tags/list

      - name: 'Download Dynatrace Configuration Archive'
        uses: azure/cli@fix-161
        with:
          inlineScript: |
            az storage blob download \
              --account-name ${{ vars.TF_BACKEND_STORAGE_ACCOUNT }} \
              --container-name ${{ vars.TF_BACKEND_CONTAINER }} \
              --name ${{ inputs.target_folder }}/${{ inputs.export_file_name }}.tar.gz \
              --file ${{ inputs.target_folder }}/${{ inputs.export_file_name }}.tar.gz" \
              --auth-mode key \
              --account-key ${{ secrets.ARM_ACCESS_KEY }}

      - name: 'Extract Dynatrace Configuration Archive'
        env:
            ARCHIVE: ${{ inputs.target_folder }}
        run: |
          ls -las ${{ inputs.target_folder }}
          ls -las "$RUNNER_TEMP/${{ inputs.target_folder }}"
          tar -xzvf ${{ inputs.target_folder }}/${{ inputs.export_file_name }}.tar.gz -C "$RUNNER_TEMP/${{ inputs.target_folder }}"
          ls -las "$RUNNER_TEMP/${{ inputs.target_folder }}"
        working-directory: ${{ inputs.target_folder }}

      - name: 'Upload directory as artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIR_ARTIFACT_NAME }}
          path: ${{ inputs.target_folder }}/**
          include-hidden-files: true
          retention-days: 1