name: "Dynatrace Configuration Deploy"

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: "Source Dynatrace environment"
        required: true
        type: choice
        options:
          - yhu28601
          - val72867
          - vtq72629
          - avc65257
          - jqa38275
          - rwb66447
          - yyo96051
        default: yhu28601
      target_environment:
        description: "Target Dynatrace environment"
        required: true
        type: choice
        options:
          - nyw40909
          - bkh87134
          - zpa13569
          - bse40162
          - jkf42365
          - tqe98595
          - sxd52035
          - sby39331
        default: nyw40909
      format:
        description: "Export format"
        required: true
        type: choice
        options:
          - monaco
          - terraform
        default: monaco
      storage:
        description: "Source storage type"
        required: true
        type: choice
        options:
          - azure-blob
          - github-repo
        default: azure-blob
      artifact_name:
        description: "Source Configuration File or Github Repo Branch Name"
        required: true
        type: string
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - dry-run
          - deploy
        #  - delete
        default: dry-run

concurrency:
  group: deploy-${{ github.event.inputs.source_environment }}-to-${{ github.event.inputs.target_environment }}
  cancel-in-progress: false

jobs:
  dynatrace_deploy_configuration:
    name: Dynatrace Deploy ${{ github.event.inputs.monaco_action }} [${{ github.event.inputs.target_environment }}]
    runs-on: ubuntu-latest

    # GitHub Repo Environments can be used to protect against accidental deployments to production and to provide environment-specific secrets and variables.
    # By setting the environment in the workflow, you can leverage these features.
    environment: ${{ github.event.inputs.target_environment }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DYNATRACE_ENV_URL: ${{ vars.DYNATRACE_ENV_URL }}
      DT_CLIENT_ID: ${{ secrets.DT_CLIENT_ID }}
      DT_CLIENT_SECRET: ${{ secrets.DT_CLIENT_SECRET }}
      TARGET_FOLDER: environments/${{ github.event.inputs.source_environment }}/data
      DIR_ARTIFACT_NAME: export-dir-artifact

    outputs:
      build_timestamp: ${{ steps.build_timestamp.outputs.version }}
      target_folder: ${{ env.TARGET_FOLDER }}
      tf_backend_storage_account: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT }}
      tf_backend_container: ${{ vars.TF_BACKEND_CONTAINER }}
      dir_artifact_name: ${{ env.DIR_ARTIFACT_NAME }}
      gh_repo_owner: ${{ vars.GH_REPO_OWNER }}
      gh_repo_name: ${{ vars.GH_REPO_NAME }}
      dynatrace_env_url: ${{ env.DYNATRACE_ENV_URL }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

  download_from_azure:
    needs: [dynatrace_deploy_configuration]
    uses: ./.github/workflows/azure_blob_download.yaml
    if: (github.event.inputs.storage == 'azure-blob') && contains(needs.*.result, 'success')
    with:
      environment: ${{ github.event.inputs.source_environment }}
      target_folder: ${{ needs.dynatrace_deploy_configuration.outputs.target_folder }}
      export_file_name: ${{ github.event.inputs.artifact_name }}
      tf_backend_storage_account: ${{ needs.dynatrace_deploy_configuration.outputs.tf_backend_storage_account }}
      tf_backend_container: ${{ needs.dynatrace_deploy_configuration.outputs.tf_backend_container }}
      dir_artifact_name: ${{ needs.dynatrace_deploy_configuration.outputs.dir_artifact_name }}
    secrets: inherit

  checkout_from_github:
    needs: [ dynatrace_deploy_configuration ]
    uses: ./.github/workflows/github_repo_download.yaml
    if: (github.event.inputs.storage == 'github-repo') && contains(needs.*.result, 'success')
    with:
      environment: ${{ github.event.inputs.source_environment }}
      target_folder: ${{ needs.dynatrace_deploy_configuration.outputs.target_folder }}
      gh_branch_name: ${{ github.event.inputs.artifact_name }}
      gh_repo_name: ${{ needs.dynatrace_deploy_configuration.outputs.gh_repo_name }}
      gh_repo_owner: ${{ needs.dynatrace_deploy_configuration.outputs.gh_repo_owner }}
      dir_artifact_name: ${{ needs.dynatrace_deploy_configuration.outputs.dir_artifact_name }}
    secrets: inherit

  monaco_deploy:
    needs: [ dynatrace_deploy_configuration, download_from_azure, checkout_from_github ]
    uses: ./.github/workflows/dynatrace_monaco_deploy.yaml
    if: |
      always() &&
      github.event.inputs.format == 'monaco' &&
      (needs.download_from_azure.result == 'success' || needs.checkout_from_github.result == 'success')
    with:
      target_environment: ${{ github.event.inputs.target_environment }}
      action: ${{ github.event.inputs.action }}
      dynatrace_env_url: ${{ needs.dynatrace_deploy_configuration.outputs.dynatrace_env_url }}
      dir_artifact_name: ${{ needs.dynatrace_deploy_configuration.outputs.dir_artifact_name }}
      target_folder: ${{ needs.dynatrace_deploy_configuration.outputs.target_folder }}
    secrets: inherit

  terraform_deploy:
    needs: [ dynatrace_deploy_configuration, download_from_azure, checkout_from_github ]
    uses: ./.github/workflows/dynatrace_terraform_deploy.yaml
    if: |
      always() &&
      github.event.inputs.format == 'terraform' &&
      (needs.download_from_azure.result == 'success' || needs.checkout_from_github.result == 'success')
    with:
      target_environment: ${{ github.event.inputs.target_environment }}
      action: ${{ github.event.inputs.action }}
      dynatrace_env_url: ${{ needs.dynatrace_deploy_configuration.outputs.dynatrace_env_url }}
      dir_artifact_name: ${{ needs.dynatrace_deploy_configuration.outputs.dir_artifact_name }}
      target_folder: ${{ needs.dynatrace_deploy_configuration.outputs.target_folder }}
      tf_backend_storage_account: ${{ needs.dynatrace_deploy_configuration.outputs.tf_backend_storage_account }}
      tf_backend_container: ${{ needs.dynatrace_deploy_configuration.outputs.tf_backend_container }}
    secrets: inherit
