name: "Dynatrace Monaco Provider Deploy"

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      action:
        required: true
        type: string
      dir_artifact_name:
        required: true
        type: string
      target_folder:
        required: true
        type: string
      dynatrace_env_url:
        required: true
        type: string

jobs:
  dynatrace_monaco_deploy:
    name: Dynatrace Monaco ${{ inputs.action }} [${{ inputs.target_environment }}]
    runs-on: ubuntu-latest

    environment: ${{ inputs.target_environment }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DYNATRACE_ENV_URL:  ${{ inputs.dynatrace_env_url }}
      DT_CLIENT_ID: ${{ secrets.DT_CLIENT_ID }}
      DT_CLIENT_SECRET: ${{ secrets.DT_CLIENT_SECRET }}
      DT_ACCOUNT_ID: ${{ vars.DT_ACCOUNT_ID }}
      TARGET_FOLDER:  ${{ inputs.target_folder }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Download directory artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.dir_artifact_name }}
          path: ${{ env.TARGET_FOLDER }}

      - name: 'Replace DYNATRACE_ENV_URL placeholder in Monaco configuration files'
        run: |
         find ${{ env.TARGET_FOLDER }} -type f -name "manifest-projects.yaml" -exec sed -i "s|DYNATRACE_ENV_URL|${{ env.DYNATRACE_ENV_URL }}|g" {} \;

      - name: 'Display manifest-projects content for debugging'
        run: |
          cat ${{ env.TARGET_FOLDER }}/manifest-projects.yaml

      - name: 'Exclude Default Dynatrace Dashboards from Deployment'
        run: |
          cp ../../../scripts/monaco/update_config.sh ./
          chmod +x ./update_config.sh
          ./update_config.sh
          cat project/document-dashboard/config.yaml
        working-directory: ${{ env.TARGET_FOLDER }}

      - name: 'Install Dynatrace Monaco Tool'
        run: |
          curl -L https://github.com/Dynatrace/dynatrace-configuration-as-code/releases/latest/download/monaco-linux-amd64 -o monaco-linux-amd64
          mv monaco-linux-amd64 monaco
          chmod +x monaco
          sudo mv monaco /usr/local/bin/
          monaco version

      - name: 'Dynatrace Monaco Projects Deploy (Dry-Run)'
        if: ${{ inputs.action == 'dry-run' }}
        run: |
          ls -las ./project
          monaco deploy manifest-projects.yaml --dry-run --continue-on-error --project project
        working-directory: ${{ env.TARGET_FOLDER }}

      - name: 'Dynatrace Monaco Projects Deploy'
        if: ${{ inputs.action == 'deploy' }}
        run: |
          ls -las ./project
          monaco deploy manifest-projects.yaml --continue-on-error --project project
        working-directory: ${{ env.TARGET_FOLDER }}

      - name: 'Dynatrace Monaco Projects Delete'
        if: ${{ inputs.action == 'delete' }}
        run: |
          monaco generate deletefile manifest-projects.yaml --project project
          cat delete.yaml
          monaco delete --manifest manifest-projects.yaml --file delete.yaml
        working-directory: ${{ env.TARGET_FOLDER }}
