name: "Dynatrace Monaco Tool Deploy"

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: "Source Dynatrace environment"
        required: true
        type: choice
        options:
          - yhu28601
        default: yhu28601
      source_export_file:
        description: "Source Dynatrace Configuration Archive File"
        required: true
        type: string
      target_environment:
        description: "Target Dynatrace environment"
        required: true
        type: choice
        options:
          - nyw40909
        default: nyw40909
      monaco_action:
        description: "Monaco action to perform"
        required: true
        type: choice
        options:
          - dry-run
        #  - deploy
        default: dry-run

# Limit concurrent runs per environment to prevent state conflicts
concurrency:
  group: monaco-export-${{ github.event.inputs.source_environment }}
  cancel-in-progress: false

jobs:
  dynatrace_export_configuration:
    name: Dynatrace Monaco ${{ github.event.inputs.monaco_action }} [${{ github.event.inputs.source_environment }}]
    runs-on: ubuntu-latest

    # GitHub Repo Environments can be used to protect against accidental deployments to production and to provide environment-specific secrets and variables.
    # By setting the environment in the workflow, you can leverage these features.
    environment: ${{ github.event.inputs.source_environment }}

    env:
      # GitHub automatically provides a GITHUB_TOKEN secret to authenticate API requests made by the workflow.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Dynatrace environment URL and API token — also stored as secrets in GitHub environments.
      DYNATRACE_ENV_URL: ${{ vars.DYNATRACE_ENV_URL }}
      # Dynatrace OAuth2 Client (Source)
      DT_CLIENT_ID: ${{ secrets.DT_CLIENT_ID }}
      DT_CLIENT_SECRET: ${{ secrets.DT_CLIENT_SECRET }}
      DT_ACCOUNT_ID: ${{ secrets.DT_ACCOUNT_ID }}
      # Dynatrace Monaco Tool Export Target Folder
      MONACO_TARGET_FOLDER: environments/${{ github.event.inputs.source_environment }}/monaco
      MONACO_EXPORT_ZIP_FILE_NAME_PREFIX: monaco-${{ github.event.inputs.source_environment }}
      # Azure Service Principal credentials — stored as secrets in each
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ${{ env.MONACO_TARGET_FOLDER }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Download zip to Azure Blob Storage'
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob download \
              --account-name ${{ vars.TF_BACKEND_STORAGE_ACCOUNT }} \
              --container-name ${{ vars.TF_BACKEND_CONTAINER }} \
              --name $MONACO_TARGET_FOLDER/${{ github.event.inputs.source_export_file }}.tar.gz \
              --file $MONACO_TARGET_FOLDER/${{ github.event.inputs.source_export_file }}.tar.gz \
              --auth-mode key \
              --account-key $ARM_ACCESS_KEY

      - name: 'List Downloaded Files'
        run: |
          ls -la $MONACO_TARGET_FOLDER

      - name: 'Unpack Dynatrace Configuration Archive'
        run: |
          tar -czf $MONACO_TARGET_FOLDER/$MONACO_EXPORT_ZIP_FILE_NAME_PREFIX-${{ env.BUILD_TIMESTAMP }}.tar.gz -C ./generated .
          rm $MONACO_TARGET_FOLDER/.generated/manifest.yaml
          cat <<EOF > $MONACO_TARGET_FOLDER/.generated/manifest.yaml
          manifestVersion: "1.0"
          projects:
            - name: accounts
            - name: dt-migration-project
              path: project
          environmentGroups:
            - name: target
              environments:
                - name: ${{ github.event.inputs.target_environment }}
                  url:
                    type: environment
                    value: DYNATRACE_ENV_URL
                  oAuth:
                    clientId:
                      type: environment
                      name: DT_CLIENT_ID
                    clientSecret:
                      type: environment
                      name: DT_CLIENT_SECRET
          accounts:
            - name: account_${DT_ACCOUNT_ID}
              accountUUID:
                value: ${DT_ACCOUNT_ID}
              oAuth:
                clientId:
                  type: environment
                  name: DT_CLIENT_ID
                clientSecret:
                  type: environment
                  name: DT_CLIENT_SECRET
          EOF
          ls -la $MONACO_TARGET_FOLDER/.generated
          cat $MONACO_TARGET_FOLDER/.generated/manifest.yaml

      - name: 'Install Dynatrace Monaco Tool'
        run: |
          curl -L https://github.com/Dynatrace/dynatrace-configuration-as-code/releases/latest/download/monaco-linux-amd64 -o monaco-linux-amd64
          mv monaco-linux-amd64 monaco
          chmod +x monaco
          sudo mv monaco /usr/local/bin/
          monaco version

      - name: 'Dynatrace Monaco Account Deploy (Dry-Run)'
        if: ${{ github.event.inputs.monaco_action == 'dry-run' }}
        run: |
          monaco account deploy 
            --dry-run \
            --manifest $MONACO_TARGET_FOLDER/.generated/manifest.yaml \
            --account $DT_ACCOUNT_ID \
            --oauth-client-id DT_CLIENT_ID \
            --oauth-client-secret DT_CLIENT_SECRET \

      - name: 'Dynatrace Monaco Configuration Deploy (Dry-Run)'
        if: ${{ github.event.inputs.monaco_action == 'dry-run' }}
        run: |
          monaco deploy 
            --dry-run \
            --manifest $MONACO_TARGET_FOLDER/.generated/manifest.yaml \
            --environment ${{ github.event.inputs.target_environment }} \
            --project dt-migration-project \
            --oauth-client-id DT_CLIENT_ID \
            --oauth-client-secret DT_CLIENT_SECRET \